CREATE VIEW dbo.VW_PACIENTES
AS
SELECT IDPACIENTE,
       NOMBRE1,
       NOMBRE2,
       APELLIDO1,
       APELLIDO2,
       FECHANACIMIENTO,
       TELEFONO,
       ACTIVO,
	   SUBSTRING(NOMBRE1, 1, 1) AS INICIALNOMBRE,
	   SUBSTRING(APELLIDO1, 1, 1) AS INICIALAPELLIDO,
	   LEN(NOMBRE1) AS LONGITUDNOMBRE1,
	   LEN(APELLIDO1) AS LONGITUDAPELLIDO1,
		SUBSTRING(NOMBRE1, LEN(NOMBRE1) ,1) AS ULTIMALETRA
	   FROM dbo.TB_PACIENTES




ALTER VIEW dbo.VW_PACIENTES
AS
SELECT IDPACIENTE,
       NOMBRE1,
       NOMBRE2,
       APELLIDO1,
       APELLIDO2,
       FECHANACIMIENTO,
       TELEFONO,
       ACTIVO,
	   SUBSTRING(NOMBRE1, 1, 1) AS INICIALNOMBRE,
	   SUBSTRING(APELLIDO1, 1, 1) AS INICIALAPELLIDO,
	   LEN(NOMBRE1) AS LONGITUDNOMBRE1,
	   LEN(APELLIDO1) AS LONGITUDAPELLIDO1,
		SUBSTRING(NOMBRE1, LEN(NOMBRE1) ,1) AS ULTIMALETRA,
		 ISNULL(NOMBRE1,'') + ' ' + ISNULL(NOMBRE2,'') + ' ' + ISNULL(APELLIDO1,'') + ' ' + ISNULL(APELLIDO2,'') AS NOMBRECOMPLETO,
		  dbo.FNN_INICIALES(NOMBRE1, APELLIDO1) AS INCIALES
	   FROM dbo.TB_PACIENTES
