--SELECT *, INICIALNOMBRE + INICIALAPELLIDO
--	   FROM dbo.VW_PACIENTES

|

CREATE FUNCTION dbo.FNN_INICIALES(@NOMBRE1 VARCHAR(200), @APELLIDO1 VARCHAR(200))
RETURNS CHAR(2)
AS
BEGIN
DECLARE @INICIALES CHAR(2)
SELECT @INICIALES = SUBSTRING(@NOMBRE1, 1, 1) +  SUBSTRING(@APELLIDO1, 1, 1) 
RETURN @INICIALES
END


SELECT *, dbo.FNN_INICIALES(NOMBRE1, APELLIDO1) FROM dbo.TB_PACIENTES

SELECT * FROM dbo.VW_PACIENTES

