SELECT * FROM dbo.TB_PACIENTES

DECLARE @MENSAJE VARCHAR(200),
        @BOLVALIDO BIT

EXEC dbo.SSP_DELPACIENTE @IDPACIENTE = 11, @MENSAJE = @MENSAJE OUTPUT, @BOLVALIDO = @BOLVALIDO OUTPUT

SELECT @MENSAJE, @BOLVALIDO
				