CREATE TABLE dbo.TB_PACIENTES (
	IDPACIENTE INT PRIMARY KEY IDENTITY (1,1),
	NOMBRE1 VARCHAR(200),
	NOMBRE2 VARCHAR(200),
	APELLIDO1 VARCHAR(200),
	APELLIDO2 VARCHAR(200),
	FECHANACIMIENTO DATE,
	TELEFONO VARCHAR(200),
	ACTIVO BIT
)


