--JOIN INTERSECCIN ENTRE DOS CONJUNTOS DE DATOS

SELECT * FROM dbo.TB_PACIENTES WHERE IDPACIENTE = 1

SELECT * FROM dbo.TB_SOLICITUDES WHERE IDPACIENTE = 1


SELECT * FROM dbo.TB_PACIENTES AS X
JOIN dbo.TB_SOLICITUDES AS Y 
ON X.IDPACIENTE = Y.IDPACIENTE
WHERE X.IDPACIENTE = 1


SELECT X.IDPACIENTE, COUNT(Y.IDSOLICITUD) AS CANTIDAD
FROM dbo.TB_PACIENTES AS X
JOIN dbo.TB_SOLICITUDES AS Y 
ON X.IDPACIENTE = Y.IDPACIENTE
GROUP BY X.IDPACIENTE
HAVING COUNT(Y.IDSOLICITUD) > 1


--LEFT JOIN, INTERSECCION QUE CRUCE O NO


SELECT * FROM dbo.TB_PACIENTES WHERE IDPACIENTE = 16

SELECT * FROM dbo.TB_SOLICITUDES WHERE IDPACIENTE = 16

SELECT X.IDPACIENTE, Y.IDSOLICITUD FROM dbo.TB_PACIENTES AS X
JOIN dbo.TB_SOLICITUDES AS Y
ON Y.IDPACIENTE = X.IDPACIENTE

SELECT X.IDPACIENTE, Y.IDSOLICITUD FROM dbo.TB_PACIENTES AS X
LEFT JOIN dbo.TB_SOLICITUDES AS Y
ON Y.IDPACIENTE = X.IDPACIENTE

SELECT X.IDPACIENTE, Y.IDSOLICITUD FROM dbo.TB_PACIENTES AS X
LEFT JOIN dbo.TB_SOLICITUDES AS Y
ON Y.IDPACIENTE = X.IDPACIENTE
WHERE Y.IDSOLICITUD IS NULL