SELECT YEAR(L.FECHASOLICITUD) AS ANO,
		MONTH(L.FECHASOLICITUD) AS MES,
		DAY(L.FECHASOLICITUD) AS DIA,
	   COUNT(L.IDSOLICITUD) AS CANTIDAD
	FROM GENERAL.TB_PACIENTES AS P
    JOIN GENERAL.TB_TIPOSIDENTIFICACION AS T
        ON T.IDTIPOIDENTIFICACION = P.IDTIPOIDENTIFICACION
    JOIN GENERAL.TB_SEXO AS S
        ON S.IDSEXO = P.IDSEXO
     JOIN LABORATORIO.VW_CABSOLICITUD AS L
        ON L.IDPACIENTE = P.IDPACIENTE
	GROUP BY YEAR(L.FECHASOLICITUD), MONTH(L.FECHASOLICITUD), DAY(L.FECHASOLICITUD)
	ORDER BY 1, 2, 3



SELECT P.IDPACIENTE, COUNT(L.IDSOLICITUD) AS CANTIDAD
FROM GENERAL.TB_PACIENTES AS P
JOIN GENERAL.TB_TIPOSIDENTIFICACION AS T
    ON T.IDTIPOIDENTIFICACION = P.IDTIPOIDENTIFICACION
JOIN GENERAL.TB_SEXO AS S
    ON S.IDSEXO = P.IDSEXO
    JOIN LABORATORIO.VW_CABSOLICITUD AS L
    ON L.IDPACIENTE = P.IDPACIENTE
	GROUP BY P.IDPACIENTE
	