SELECT PAC.IDPACIENTE,
       PAC.CANTIDAD,
       PACI.NOMBRE1,
       PACI.NUMEROIDENTIFICACION
FROM
(
    SELECT P.IDPACIENTE,
           COUNT(L.IDSOLICITUD) AS CANTIDAD
    FROM GENERAL.TB_PACIENTES AS P
        JOIN GENERAL.TB_TIPOSIDENTIFICACION AS T
            ON T.IDTIPOIDENTIFICACION = P.IDTIPOIDENTIFICACION
        JOIN GENERAL.TB_SEXO AS S
            ON S.IDSEXO = P.IDSEXO
        JOIN LABORATORIO.VW_CABSOLICITUD AS L
            ON L.IDPACIENTE = P.IDPACIENTE
    GROUP BY P.IDPACIENTE
) AS PAC
    JOIN GENERAL.TB_PACIENTES AS PACI
        ON PACI.IDPACIENTE = PAC.IDPACIENTE


		--TIPOIDENTIFICACION, CANTIDAD ORDENADO CANTIDAD DESC