ALTER PROCEDURE dbo.SSP_INSPACIENTE (
@NUMERODOCUMENTO VARCHAR(200),
@NOMBRE1 VARCHAR(200),
@NOMBRE2 VARCHAR(200),
@APELLIDO1 VARCHAR(200),
@APELLIDO2 VARCHAR(200),
@FECHANACIMIENTO DATE,
@TELEFONO VARCHAR(200),
@ACTIVO BIT,
@EDAD SMALLINT,
@IDPACIENTE INT OUTPUT,
@MENSAJE VARCHAR(200) OUTPUT,
@BOLVALIDO BIT OUTPUT
)
AS
BEGIN

	IF NOT EXISTS(SELECT * FROM dbo.TB_PACIENTES WHERE NUMERODOCUMENTO = @NUMERODOCUMENTO)
	BEGIN
		INSERT INTO dbo.TB_PACIENTES 
		(NUMERODOCUMENTO, NOMBRE1, NOMBRE2, APELLIDO1, APELLIDO2, FECHANACIMIENTO, TELEFONO, ACTIVO, EDAD)
		VALUES
		(@NUMERODOCUMENTO, @NOMBRE1, @NOMBRE2, @APELLIDO1, @APELLIDO2, @FECHANACIMIENTO, @TELEFONO, @ACTIVO, @EDAD)

		SET @IDPACIENTE = SCOPE_IDENTITY()
		SET @MENSAJE = 'Paciente insertado correctamente'
		SET @BOLVALIDO = 1
	END
	ELSE
	BEGIN
		SET @IDPACIENTE = 0
		SET @MENSAJE = 'El paciente ya existe'
		SET @BOLVALIDO = 0
	END


END

