

ALTER PROCEDURE dbo.SSP_SETPACIENTE (
@IDPACIENTE INT,
@NUMERODOCUMENTO VARCHAR(200),
@NOMBRE1 VARCHAR(200),
@NOMBRE2 VARCHAR(200),
@APELLIDO1 VARCHAR(200),
@APELLIDO2 VARCHAR(200),
@FECHANACIMIENTO DATE,
@TELEFONO VARCHAR(200),
@ACTIVO BIT,
@EDAD SMALLINT,
@MENSAJE VARCHAR(200) OUTPUT,
@BOLVALIDO BIT OUTPUT
)
AS
BEGIN

	IF EXISTS (SELECT * FROM dbo.TB_PACIENTES WHERE IDPACIENTE = @IDPACIENTE)
	BEGIN

		IF NOT EXISTS (SELECT * FROM dbo.TB_PACIENTES WHERE NUMERODOCUMENTO = @NUMERODOCUMENTO)
		BEGIN
			UPDATE dbo.TB_PACIENTES SET 
			NOMBRE1 = @NOMBRE1,
			NOMBRE2 = @NOMBRE2,
			APELLIDO1 = @APELLIDO1,
			APELLIDO2 = @APELLIDO2,
			FECHANACIMIENTO = @FECHANACIMIENTO,
			TELEFONO = @TELEFONO,
			ACTIVO = @ACTIVO,
			EDAD = @EDAD,
			NUMERODOCUMENTO = @NUMERODOCUMENTO
			WHERE IDPACIENTE = @IDPACIENTE

			SET @MENSAJE = 'Paciente actualizado'
			SET @BOLVALIDO = 1

		END
		ELSE
		BEGIN
			
			SET @MENSAJE = 'El numero de documento ya existe'
			SET @BOLVALIDO = 0
		END



	END
	ELSE
	BEGIN
		SET @MENSAJE = 'El paciente no existe'
		SET @BOLVALIDO = 0
	END


END



