CREATE PROCEDURE SSP_GETSOLICITUDESBYIDPACIENTE (
@IDPACIENTE INT)
AS
BEGIN

SELECT * FROM dbo.TB_PACIENTES AS X
JOIN dbo.TB_SOLICITUDES AS Y 
ON X.IDPACIENTE = Y.IDPACIENTE
WHERE X.IDPACIENTE = @IDPACIENTE


END

