SELECT *,
CASE 
WHEN IMC < 18.5 THEN 'Bajo peso'
WHEN IMC BETWEEN 18.5 AND 24.9 THEN 'Normal'
WHEN IMC BETWEEN 25.0 AND 29.9 THEN 'Sobrepeso'
WHEN IMC >= 30 THEN 'Obesidad'
END AS CATEGORIAIMC
FROM dbo.TB_PACIENTES




