--AGRUPACION

SELECT NOMBRE1 FROM dbo.TB_PACIENTES
GROUP BY NOMBRE1

-- funciones

SELECT NOMBRE1, COUNT(*) AS CANTIDAD FROM dbo.TB_PACIENTES
GROUP BY NOMBRE1

--SUBSTRING EXTRAE UNA CADENA DE UN TEXTO
--LEN LONGIUTD DE UAN CADENA

SELECT IDPACIENTE,
       NOMBRE1,
       NOMBRE2,
       APELLIDO1,
       APELLIDO2,
       FECHANACIMIENTO,
       TELEFONO,
       ACTIVO,
	   SUBSTRING(NOMBRE1, 1, 1) AS INICIALNOMBRE,
	   SUBSTRING(APELLIDO1, 1, 1) AS INICIALAPELLIDO,
	   LEN(NOMBRE1) AS LONGITUDNOMBRE1,
	   LEN(APELLIDO1) AS LONGITUDAPELLIDO1,
		SUBSTRING(NOMBRE1, LEN(NOMBRE1) ,1) AS ULTIMALETRA
	   FROM dbo.TB_PACIENTES


--MONTH - MES
--YEAR  - AÑO
--DAY - DIA

SELECT IDPACIENTE,
       NOMBRE1,
       NOMBRE2,
       APELLIDO1,
       APELLIDO2,
       FECHANACIMIENTO,
       TELEFONO,
       ACTIVO,
	   YEAR(FECHANACIMIENTO) AS ANO,
	   MONTH(FECHANACIMIENTO) AS MES,
	   DAY(FECHANACIMIENTO) AS DIA
	   FROM dbo.TB_PACIENTES
	   WHERE YEAR(FECHANACIMIENTO) > 1990


