--ORDENAMIENTO
SELECT * FROM dbo.TB_PACIENTES

--ORDER BY

SELECT * FROM dbo.TB_PACIENTES ORDER BY EDAD DESC

--

SELECT * FROM dbo.TB_PACIENTES ORDER BY NOMBRE1, APELLIDO1 ASC

SELECT * FROM dbo.TB_PACIENTES ORDER BY YEAR(FECHANACIMIENTO)  ASC


SELECT * FROM dbo.TB_PACIENTES ORDER BY LEN(APELLIDO1) DESC
